package com.zhongruan.android.zkfingerdemo.db;

import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;

import com.zhongruan.android.zkfingerdemo.db.entity.Sn_number;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "sn_number".
*/
public class Sn_numberDao extends AbstractDao<Sn_number, Long> {

    public static final String TABLENAME = "sn_number";

    /**
     * Properties of entity Sn_number.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public final static Property Snid = new Property(0, Long.class, "snid", true, "snid");
        public final static Property Sn = new Property(1, String.class, "sn", false, "sn");
    }


    public Sn_numberDao(DaoConfig config) {
        super(config);
    }
    
    public Sn_numberDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"sn_number\" (" + //
                "\"snid\" INTEGER PRIMARY KEY AUTOINCREMENT ," + // 0: snid
                "\"sn\" TEXT);"); // 1: sn
    }

    /** Drops the underlying database table. */
    public static void dropTable(Database db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"sn_number\"";
        db.execSQL(sql);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, Sn_number entity) {
        stmt.clearBindings();
 
        Long snid = entity.getSnid();
        if (snid != null) {
            stmt.bindLong(1, snid);
        }
 
        String sn = entity.getSn();
        if (sn != null) {
            stmt.bindString(2, sn);
        }
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, Sn_number entity) {
        stmt.clearBindings();
 
        Long snid = entity.getSnid();
        if (snid != null) {
            stmt.bindLong(1, snid);
        }
 
        String sn = entity.getSn();
        if (sn != null) {
            stmt.bindString(2, sn);
        }
    }

    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    @Override
    public Sn_number readEntity(Cursor cursor, int offset) {
        Sn_number entity = new Sn_number( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // snid
            cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1) // sn
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, Sn_number entity, int offset) {
        entity.setSnid(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setSn(cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1));
     }
    
    @Override
    protected final Long updateKeyAfterInsert(Sn_number entity, long rowId) {
        entity.setSnid(rowId);
        return rowId;
    }
    
    @Override
    public Long getKey(Sn_number entity) {
        if(entity != null) {
            return entity.getSnid();
        } else {
            return null;
        }
    }

    @Override
    public boolean hasKey(Sn_number entity) {
        return entity.getSnid() != null;
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
}
